/**
 * Tailwind theme extension generated from MoodboardDesign.
 * styleThesis: Botanical Dimensional UI: Clay Diorama + Neumorphic + Editorial Commerce
 * sourceCount: 10
 * clusters: Matte Clay 3D Botanical Diorama UI / Neumorphic Soft-Extrusion Mobile UI / Editorial Botanical Commerce (Light Background) / Dark Forest-Green Botanical Product Showcase / Artisanal Flat Parchment Café UI
 *
 * Generated by designlang-vision M3 tailwind-config emitter.
 * Editing this file by hand is fine — re-running M3 will overwrite it.
 */
// NOTE: the following shadow tokens are filter:drop-shadow() — apply via
// className="[filter:drop-shadow(...)]" or a custom CSS layer, not boxShadow.
//   clay-contact: drop-shadow(0 6px 8px rgba(0,0,0,0.15))

// NOTE: typography tokens are style descriptions (not font-family/font-size pairs);
// they appear here as guidance for choosing actual font stacks.
//   heading-clay: geometric sans-serif, light–regular weight, wide tracking, low contrast
//   heading-editorial: humanist serif or calligraphic script, italic, warm off-white on dark green
//   body-universal: geometric sans-serif, light weight, tight line-height, low contrast
//   letterSpacing-heading: 0.04em–0.06em
//   letterSpacing-body: 0em–0.01em

/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {
        'green-light': '#88C4A0',
        'green-mid': '#5A8A6A',
        'green-deep': '#4A7C59',
        'green-forest': '#2D5A3D',
        'green-darkest': '#1A3D2B',
        'peach-coral': '#F4A070',
        'warm-cream': '#F5F0E8',
        'warm-beige': '#F0E6DC',
        parchment: '#F5F0E6',
        'off-white': '#FAFAF8',
        'neutral-grey': '#E8E8E8',
        'gold-accent': '#C8A84B',
        'red-accent-sparingly': '#C0392B',
        'orange-cta': '#FF5722',
        surface: {
          'clay-background': '#F8FAF8',
          'clay-card': '#FAFAF8',
          'neumorphic-base': '#E8E8E8',
          'dark-studio': '#1A3D2B',
          'parchment-base': '#F5F0E6'
        }
      },
      borderRadius: {
        'tile-sm': '12px',
        'card-md': '16px',
        'card-lg': '24px',
        pill: '999px',
        circle: '50%'
      },
      boxShadow: {
        'clay-card': '0 12px 40px rgba(0,0,0,0.10)',
        'clay-tile': '0 4px 12px rgba(0,0,0,0.08)',
        'clay-button': '0 4px 10px rgba(0,0,0,0.10)',
        'neumorphic-raised': '-4px -4px 10px #ffffff, 4px 4px 10px rgba(0,0,0,0.12)',
        'neumorphic-inset': 'inset 2px 2px 5px rgba(0,0,0,0.10), inset -2px -2px 5px #ffffff',
        'editorial-minimal': '0 1px 4px rgba(0,0,0,0.06)'
      }
    },
  },
};
