// Template emitter: MoodboardDesign → Tailwind config (theme.extend).
//
// Output is valid Node CommonJS. The caller can `require()` it from a project's
// tailwind.config.js or import via the v4 @config directive. We deliberately
// produce a config that's a single self-contained object — no peer dependencies.
//
// Mapping rules:
//   tokens.color + tokens.surface → theme.extend.colors
//   tokens.borderRadius           → theme.extend.borderRadius
//   tokens.shadow                 → theme.extend.boxShadow (only the simple ones — neumorphic-style multi-shadow strings come through as-is; inset/drop-shadow filters skipped with a comment)
//   tokens.typography (style strings) → not Tailwind-mappable directly; emitted as a header comment only

const TAILWIND_HEADER = (design) => `/**
 * Tailwind theme extension generated from MoodboardDesign.
 * styleThesis: ${escapeForComment(design.styleThesis)}
 * sourceCount: ${design.sourceCount}
 * clusters: ${(design.clusters || []).map((c) => c.name).join(' / ')}
 *
 * Generated by designlang-vision M3 tailwind-config emitter.
 * Editing this file by hand is fine — re-running M3 will overwrite it.
 */
`;

export function emitTailwindConfig(design, _opts = {}) {
  const tokens = design.tokens || {};

  const colors = {};
  for (const [name, value] of Object.entries(tokens.color || {})) {
    colors[name] = value;
  }
  if (tokens.surface) {
    colors.surface = { ...tokens.surface };
  }

  const borderRadius = {};
  for (const [name, value] of Object.entries(tokens.borderRadius || {})) {
    borderRadius[name] = value;
  }

  // Tailwind's boxShadow accepts simple css strings. Drop-shadow filter strings
  // (like "filter: drop-shadow(...)") are NOT box-shadows — emit them as comments
  // in the output so a developer can pick them up but they don't break tailwind.
  const boxShadow = {};
  const filterDropShadow = {};
  for (const [name, value] of Object.entries(tokens.shadow || {})) {
    if (/drop-shadow\(/.test(value)) {
      // Strip leading "filter: " if present, store the raw filter for documentation
      filterDropShadow[name] = value.replace(/^filter:\s*/, '');
    } else {
      boxShadow[name] = value;
    }
  }

  const themeExtend = {};
  if (Object.keys(colors).length)       themeExtend.colors       = colors;
  if (Object.keys(borderRadius).length) themeExtend.borderRadius = borderRadius;
  if (Object.keys(boxShadow).length)    themeExtend.boxShadow    = boxShadow;

  let body = TAILWIND_HEADER(design);
  if (Object.keys(filterDropShadow).length) {
    body += `// NOTE: the following shadow tokens are filter:drop-shadow() — apply via\n`;
    body += `// className="[filter:drop-shadow(...)]" or a custom CSS layer, not boxShadow.\n`;
    for (const [name, value] of Object.entries(filterDropShadow)) {
      body += `//   ${name}: ${value}\n`;
    }
    body += `\n`;
  }

  // Typography tokens are style-description strings from the M2 synthesizer
  // (e.g. "geometric sans-serif, light weight, low contrast"). We resolve them
  // to concrete font-family fallback stacks based on detected style hints,
  // then emit BOTH as a `fontFamily` token (concrete, usable) AND as a
  // header comment retaining the original style description (still useful as
  // a font-choice guide). Closes validation finding #C1-4.
  const fontFamily = {};
  if (tokens.typography) {
    body += `// NOTE: typography tokens originate as style descriptions; emitted below as\n`;
    body += `// fontFamily keys with sensible system-font fallback stacks. Swap for your\n`;
    body += `// chosen typefaces (e.g. Inter for geometric sans, Fraunces for serif) without\n`;
    body += `// changing key names — the rest of the design system references these names.\n`;
    for (const [name, description] of Object.entries(tokens.typography)) {
      const stack = guessFontStack(String(description));
      fontFamily[name] = stack;
      body += `//   ${name}: ${escapeForComment(String(description))} → ${stack.join(', ')}\n`;
    }
    body += `\n`;
  }
  if (Object.keys(fontFamily).length) {
    themeExtend.fontFamily = fontFamily;
  }

  body += `/** @type {import('tailwindcss').Config} */\n`;
  body += `module.exports = {\n`;
  body += `  // Tailwind v3 requires \`content\` to discover which class names exist in your\n`;
  body += `  // source files. The default below scans common web-project layouts; adjust\n`;
  body += `  // for your project structure (App Router uses 'app/**', Vue uses '*.vue', etc.).\n`;
  body += `  content: [\n`;
  body += `    './index.html',\n`;
  body += `    './src/**/*.{html,js,jsx,ts,tsx,vue,svelte,astro,mdx}',\n`;
  body += `    './app/**/*.{html,js,jsx,ts,tsx,vue,svelte,astro,mdx}',\n`;
  body += `    './pages/**/*.{html,js,jsx,ts,tsx,vue,svelte,astro,mdx}',\n`;
  body += `    './components/**/*.{html,js,jsx,ts,tsx,vue,svelte,astro,mdx}',\n`;
  body += `  ],\n`;
  body += `  theme: {\n`;
  body += `    extend: ${stringifyJsObject(themeExtend, '    ').trimStart()},\n`;
  body += `  },\n`;
  body += `};\n`;

  return body;
}

function escapeForComment(s) {
  return String(s).replace(/\*\//g, '*∕'); // avoid prematurely closing the /* */ block
}

// Minimal js-object stringifier that's deterministic, uses single quotes, indents nicely.
// Avoids JSON.stringify's double quotes which look ugly next to neighbouring JS code.
function stringifyJsObject(obj, indent = '') {
  if (obj === null) return 'null';
  if (Array.isArray(obj)) {
    if (obj.length === 0) return '[]';
    return '[\n' + obj.map((v) => indent + '  ' + stringifyJsValue(v, indent + '  ')).join(',\n') + '\n' + indent + ']';
  }
  if (typeof obj === 'object') {
    const keys = Object.keys(obj);
    if (keys.length === 0) return '{}';
    const lines = keys.map((k) => `${indent}  ${quoteKey(k)}: ${stringifyJsValue(obj[k], indent + '  ')}`);
    return '{\n' + lines.join(',\n') + '\n' + indent + '}';
  }
  return stringifyJsValue(obj, indent);
}

function stringifyJsValue(v, indent) {
  if (v === null) return 'null';
  if (typeof v === 'number' || typeof v === 'boolean') return String(v);
  if (typeof v === 'string') return `'${v.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
  if (Array.isArray(v) || typeof v === 'object') return stringifyJsObject(v, indent);
  return JSON.stringify(v);
}

function quoteKey(k) {
  return /^[A-Za-z_$][\w$]*$/.test(k) ? k : `'${k.replace(/'/g, "\\'")}'`;
}

/** Map a synthesizer-style typography description (e.g. "geometric sans-serif, light
 *  weight, low contrast" / "humanist serif, italic accents" / "vintage script") to a
 *  concrete CSS font-family stack starting with a sensible suggested face and ending
 *  in safe system fallbacks. The point is that a developer importing this config gets
 *  fontFamily tokens that *render* immediately, while still being labeled with the
 *  cluster's intended type personality. */
function guessFontStack(description) {
  const d = String(description).toLowerCase();
  // The classification order matters: "sans-serif" contains "serif" as a substring,
  // so we MUST detect sans first (anywhere in the description) and only fall to
  // serif branches when no sans signal is present.
  const hasSans = /\bsans\b|sans-serif/.test(d);
  const hasSerif = /\bserif\b/.test(d) && !hasSans;

  if (/mono|monospace|code|tabular/.test(d)) {
    return ['JetBrains Mono', 'IBM Plex Mono', 'ui-monospace', 'SFMono-Regular', 'Menlo', 'monospace'];
  }
  if (hasSans) {
    if (/(humanist|warm|rounded|soft)/.test(d)) {
      return ['Manrope', 'DM Sans', 'system-ui', '-apple-system', 'Helvetica Neue', 'sans-serif'];
    }
    // Default sans → geometric (Inter is the safe modern default)
    return ['Inter', 'Mona Sans', 'system-ui', '-apple-system', 'BlinkMacSystemFont', 'Helvetica Neue', 'Arial', 'sans-serif'];
  }
  if (hasSerif) {
    if (/(humanist|transitional|old.?style|garamond|caslon|book)/.test(d)) {
      return ['Cormorant Garamond', 'EB Garamond', 'Source Serif Pro', 'Georgia', 'ui-serif', 'serif'];
    }
    if (/(script|calligraph|handwritten|cursive|italic)/.test(d)) {
      return ['Cormorant Garamond', 'Playfair Display', 'Lora', 'Georgia', 'ui-serif', 'serif'];
    }
    return ['Fraunces', 'Source Serif Pro', 'Georgia', 'ui-serif', 'serif'];
  }
  // No sans / serif signal: default to clean geometric system sans
  return ['Inter', 'system-ui', '-apple-system', 'BlinkMacSystemFont', 'Helvetica Neue', 'Arial', 'sans-serif'];
}
